### ISSUE TITLE
Duplicate version file

### ISSUE THREAD

**Issue by HebaruSan** [zer0Kerbal/Notes#45]
0.17.0.0 failed to be added to CKAN because it has two copies of its version file:

![image](https://user-images.githubusercontent.com/1559108/160121558-8b9e849e-22fa-466c-a17e-382f0ddc682b.png)

![image](https://user-images.githubusercontent.com/1559108/160121569-c83f274f-be9b-48d5-b03c-354d628ff28b.png)

They're identical except for the `NAME`, as far as I can tell. Suggest removing `notesRPM.version` to fix this, as it doesn't look like it's needed.

Tagging @zer0Kerbal to make sure GItHub sends notifications.

**Comment by HebaruSan** [comment]
Yeah, I saw the boilerplate. Please don't waste more of my time with it.

**Comment by zer0Kerbal** [comment]
> @zer0Kerbal, I'm sorry that I reacted that way; I woke up feeling irritable today (sirens speeding past the house can do that) and I should not have taken that out on you. You do deserve better. I'll delete that comment.

As did I. Plus the don't give credit stuck in my sleep deprived craw. I always go out of my way to properly credit, unless I am told in writing in advance, which let's face it - that won't happen.

> 
> Aside from tone problems, though, this _is_ reporting a valid problem. Version files are **not** supposed to be one-per-DLL; they're meant to represent the compatibility of an _entire mod_, and there's no benefit from duplicating them, and in fact it could cause problems down the line. To see why, think about what would happen if you changed the `KSP_VERSION_MIN` of one file and the `KSP_VERSION_MAX` of the other file; now that they're out of sync, what is the "true" comptibility of the mod? It's not in either file, but rather has to be interpreted by combining both files somehow. If CKAN looks to just one of the files to represent the compatibility of this mod, it could well end up with incorrect metadata. Last but not least, it adds an extra maintenance burden and opportunity for errors.
> 
> I care about this because I don't want to see extra/redundant version files proliferating through a bunch more mods; better to nip it in the bud now.
> 
> Please consider fixing this. Thanks!

A new version has dropped on SpaceDock - it still is 0.17.0.0 but now with -adoption added - so it doesn't mess up the versioning for other releases.

Thank you for bringing this to my attention. _Proper credit will be given next release. ;p_

**Comment by HebaruSan** [comment]
Cool, that worked! :tada: 

https://github.com/KSP-CKAN/CKAN-meta/commit/a36b018518e554f3fc15dd04b6461a4060482c65
